d3.select('#chart')
	.append('svg')
		.attr('width', 600)
		.attr('height', 400)
		.style('background', 'gray')
	.append('rect')
		.attr('x', 200)
		.attr('y', 100)
		.attr('width', 200)
		.attr('height', 200)
		.style('fill', 'darkorange')
	d3.select('svg')
		.append('circle')
			.attr('cx', 300)
			.attr('cy', 200)
			.attr('r', 50)
			.style('fill', 'purple');